import type { JevAgentId, JevAnswer } from "./questions";

/**
 * Stored results, served when the cap is reached or a live call fails.
 *
 * Generated by scripts/capture-jev.mjs from real calls on 2026-09-26. Do not edit
 * by hand: the screen labels these "Recorded result from <date>", so every
 * value here has to be one the model actually returned.
 */

export type RecordedResult = {
  capturedOn: string | null;
  latencyMs: number | null;
  answers: JevAnswer[];
};

export const RECORDED: Record<JevAgentId, RecordedResult> = {
  "intake": {
    "capturedOn": "2026-09-26",
    "latencyMs": 533,
    "answers": [
      {
        "key": "topic",
        "type": "choice",
        "display": "billing_credits",
        "confidence": 1,
        "probability": null
      },
      {
        "key": "urgency",
        "type": "score",
        "display": "0.68",
        "confidence": 0.42,
        "probability": null
      }
    ]
  },
  "grounding-checker": {
    "capturedOn": "2026-09-26",
    "latencyMs": 677,
    "answers": [
      {
        "key": "grounded",
        "type": "boolean",
        "display": "No",
        "confidence": null,
        "probability": 0.14
      }
    ]
  },
  "escalation-router": {
    "capturedOn": "2026-09-26",
    "latencyMs": 598,
    "answers": [
      {
        "key": "queue",
        "type": "choice",
        "display": "billing",
        "confidence": 1,
        "probability": null
      }
    ]
  }
};

export function hasRecorded(id: JevAgentId) {
  return RECORDED[id].capturedOn !== null && RECORDED[id].answers.length > 0;
}
