/*
  Captures real Jev results into lib/jev/recorded.ts.

  The demo serves a stored result when the rate limit or the daily cap is hit.
  Those stored results have to come from calls that actually happened: the
  screen labels them "Recorded result from <date>", and writing a plausible
  answer by hand would be a claim about something that never ran.

  Run once AI_GATEWAY_API_KEY exists in .env.local:

    node --experimental-strip-types scripts/capture-jev.mjs

  It prints the raw provider result for each agent, so the numbers can be
  checked against what the API actually returned, then writes recorded.ts.
*/
import { readFileSync, writeFileSync } from "node:fs";
import { experimental_evaluate as evaluate } from "ai";
import { JEV_AGENTS, JEV_AGENT_IDS, JEV_MODEL } from "../lib/jev/questions.ts";

for (const line of readFileSync(".env.local", "utf8").split("\n")) {
  if (!line.trim() || line.trim().startsWith("#")) continue;
  const i = line.indexOf("=");
  if (i === -1) continue;
  process.env[line.slice(0, i).trim()] ??= line.slice(i + 1).trim();
}

if (!process.env.AI_GATEWAY_API_KEY) {
  console.error("AI_GATEWAY_API_KEY is not set in .env.local. Nothing captured.");
  process.exit(1);
}

const today = new Date().toISOString().slice(0, 10);
const captured = {};

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

/*
  The Gateway advertises a small per-window request limit for this model
  (x-ratelimit-limit-requests: 5, reset about 15s) and the upstream provider
  returns 503 under load. Three calls fired back to back hit both. Space them
  out and retry, so a capture is not lost to a transient upstream.
*/
async function evaluateWithRetry(spec, id, attempts = 5) {
  for (let attempt = 1; attempt <= attempts; attempt++) {
    try {
      // Timed around the successful attempt only. A retry wait is not latency,
      // and folding it in would publish a number the model never took.
      const started = Date.now();
      const result = await evaluate({
        model: JEV_MODEL,
        state: spec.sampleState,
        questions: spec.questions,
      });
      return { result, latencyMs: Date.now() - started };
    } catch (cause) {
      const message = String(cause?.message ?? cause).split("\n")[0];
      if (attempt === attempts) throw cause;
      const wait = 15000 * attempt;
      console.log(`  ${id}: attempt ${attempt} failed (${message}), waiting ${wait / 1000}s`);
      await sleep(wait);
    }
  }
}

let first = true;
for (const id of JEV_AGENT_IDS) {
  const spec = JEV_AGENTS[id];
  if (!first) await sleep(16000);
  first = false;
  const { result, latencyMs } = await evaluateWithRetry(spec, id);

  const confidence = result.providerMetadata?.typesafe?.confidence;

  console.log(`\n=== ${id} (${latencyMs} ms) ===`);
  console.log("answers:", JSON.stringify(result.answers, null, 2));
  console.log("confidence:", JSON.stringify(confidence ?? null));
  console.log("usage:", JSON.stringify(result.usage ?? null));

  const answers = Object.entries(result.answers).map(([key, a]) => {
    if (a.type === "boolean") {
      return {
        key,
        type: "boolean",
        display: a.probability >= 0.5 ? "Yes" : "No",
        confidence: null,
        probability: a.probability,
      };
    }
    if (a.type === "score") {
      return {
        key,
        type: "score",
        display: a.score.toFixed(2),
        confidence: confidence?.[key] ?? null,
        probability: null,
      };
    }
    return {
      key,
      type: "choice",
      display: a.choice,
      confidence: confidence?.[key] ?? null,
      probability: null,
    };
  });

  captured[id] = { capturedOn: today, latencyMs, answers };
}

const file = `import type { JevAgentId, JevAnswer } from "./questions";

/**
 * Stored results, served when the cap is reached or a live call fails.
 *
 * Generated by scripts/capture-jev.mjs from real calls on ${today}. Do not edit
 * by hand: the screen labels these "Recorded result from <date>", so every
 * value here has to be one the model actually returned.
 */

export type RecordedResult = {
  capturedOn: string | null;
  latencyMs: number | null;
  answers: JevAnswer[];
};

export const RECORDED: Record<JevAgentId, RecordedResult> = ${JSON.stringify(captured, null, 2)};

export function hasRecorded(id: JevAgentId) {
  return RECORDED[id].capturedOn !== null && RECORDED[id].answers.length > 0;
}
`;

writeFileSync("lib/jev/recorded.ts", file);
console.log(`\nWrote lib/jev/recorded.ts with ${JEV_AGENT_IDS.length} captured results from ${today}.`);
