import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Architecture diagrams | Architect 2.0",
  description:
    "Three generated diagrams: the system and its trust boundaries, the agent workflow, and one Jev call end to end.",
};

const DIAGRAMS = [
  {
    slug: "architecture",
    title: "System architecture",
    blurb:
      "What runs and what is staged, with the trust boundaries drawn. Every node says Real or Simulated, and 22 of them link to the exact file and lines at the commit the diagram was built from.",
    source: "docs/architecture/architecture.json",
  },
  {
    slug: "agent-workflow",
    title: "Agent workflow",
    blurb:
      "The four Northwind agents in the order they run, each naming the kind of model it uses and why that is the right kind for its job.",
    source: "docs/architecture/agent-workflow.json",
  },
  {
    slug: "jev-call-sequence",
    title: "Jev call sequence",
    blurb:
      "One press of Run this agent, end to end: the rate limit checked before the Gateway is touched, the call, the log write, and the recorded fallback.",
    source: "docs/architecture/jev-call-sequence.json",
  },
];

/**
 * The diagrams index.
 *
 * Exists so the demo and the diagrams link both ways: the delivered diagram
 * files are generated artifacts and cannot carry a link back into the product,
 * so this page is the hinge between them.
 *
 * Below 640px it serves a still image instead of sending a phone to a canvas
 * built for a desktop. The stills are generated by scripts/diagram-stills.mjs
 * from the delivered diagrams, so they cannot drift from what they show.
 */
export default function ArchitectureIndex() {
  return (
    <main className="mx-auto flex min-h-dvh w-full max-w-5xl flex-col gap-6 p-4 sm:p-6">
      <header className="flex flex-col gap-2">
        <p className="text-caption text-graphite">Architect 2.0</p>
        <h1 className="text-title font-semibold">Architecture diagrams</h1>
        <p className="max-w-[72ch] text-body text-graphite">
          Generated from JSON committed in the repo, not drawn by hand, and
          rebuilt before submission. A node is never marked Real unless it
          actually runs.
        </p>
        <p className="flex flex-wrap items-center gap-x-3 gap-y-1 text-caption">
          <Link href="/demo" className="text-blueprint underline">
            Back to the demo
          </Link>
          <Link href="/" className="text-blueprint underline">
            Home
          </Link>
        </p>
      </header>

      <p className="rounded-panel border border-rule p-3 text-small text-graphite sm:hidden">
        These are desktop canvases. On a phone you get the still image below,
        which is the whole diagram. Open this page on a larger screen for the
        interactive version, with zoom, search and the source links.
      </p>

      <ul className="flex flex-col gap-6">
        {DIAGRAMS.map((d) => (
          <li
            key={d.slug}
            className="flex min-w-0 flex-col gap-3 rounded-panel border border-rule p-4"
          >
            <div className="min-w-0">
              <h2 className="text-lead font-semibold">{d.title}</h2>
              <p className="mt-1 max-w-[72ch] text-small text-graphite">
                {d.blurb}
              </p>
            </div>

            {/* The still carries the whole diagram, so a phone is not sent to a
                canvas it cannot use. Hidden once there is room for the real one. */}
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img
              src={`/architecture/still/${d.slug}.png`}
              alt={`${d.title} diagram, still image`}
              width={1440}
              height={900}
              className="w-full rounded-input border border-rule sm:hidden"
            />

            <p className="flex flex-wrap items-center gap-x-3 gap-y-1 text-caption">
              <a
                href={`/architecture/${d.slug}.html`}
                className="inline-flex min-h-11 items-center rounded-input bg-blueprint px-3 text-body text-paper"
              >
                <span className="hidden sm:inline">Open the diagram</span>
                <span className="sm:hidden">Open anyway, needs a wide screen</span>
              </a>
              <span className="text-graphite">
                Source: <span className="font-mono">{d.source}</span>
              </span>
            </p>
          </li>
        ))}
      </ul>

      <p className="max-w-[72ch] text-caption text-graphite">
        One known limitation: below about 900px of viewport height the diagram
        page scrolls, and the viewer&apos;s floating toolbar then sits over the
        rightmost guided-view chip. Scrolling back up clears it. Fixing it
        properly would mean widening the canvas, which shrinks the node labels
        the same review asked to make bigger, so it is recorded rather than
        traded away. See <span className="font-mono">D45</span> in the decision
        log.
      </p>
    </main>
  );
}
